### ISSUE TITLE
AttributeError: 'VoiceClient' object has no attribute 'ws'

### ISSUE THREAD

**Issue by BinuwaraN2** [CharmingMother/kurusaki_voice#19]
```
Ignoring exception in on_message
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.6/site-packages/discord/voice_client.py", line 344, in connect
await utils.sane_wait_for(futures, timeout=timeout)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/utils.py", line 352, in sane_wait_for
raise asyncio.TimeoutError()
concurrent.futures._base.TimeoutError
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 333, in _run_event
await coro(*args, **kwargs)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 943, in on_message
await self.process_commands(message)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 940, in process_commands
await self.invoke(ctx)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 903, in invoke
await ctx.command.invoke(ctx)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 851, in invoke
 await self.prepare(ctx)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 791, in prepare
await self.call_before_hooks(ctx)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 732, in call_before_hooks
await self._before_invoke(instance, ctx)
File "/app/cogs/music.py", line 355, in before_play
return await msg.author.voice.channel.connect()
File "/app/.heroku/python/lib/python3.6/site-packages/discord/abc.py", line 1122, in connect
await voice.connect(timeout=timeout, reconnect=reconnect)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/voice_client.py", line 346, in connect
await self.disconnect(force=True)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/voice_client.py", line 460, in disconnect
if self.ws:
AttributeError: 'VoiceClient' object has no attribute 'ws'
```

How do I fix this error?

**Comment by BinuwaraN2** [comment]
It was a problem with my own code and I was able to fix it
